timescale/helm-charts

CHANGELOG.md
charts/timescaledb-multinode/Chart.yaml
charts/timescaledb-single/Chart.yaml

* A preliminary multinode Helm chart
* Architecture diagrams
* Allow multiple volumes for the data directory and the WAL directory
* Documentation pgBackRest restore outside of Kubernetes environment
* The defined Patroni configuration is passed on (using a ConfigMap) to Patroni
* Secrets required by Patroni are injected using environment variables
* The defined pgBackRest configuration is passed on to pgBackRest (using a Secret as it holds credentials)
* The entrypoint no longer points to scripts in the Docker image, this pretty much allows any Docker image
to be used, as long as it contains PostgreSQL, TimescaleDB, and pgBackRest
* Best practice PostgreSQL parameters, e.g. enable logging of connections by default
* Open Sourced this repository as Apache License 2.0

Release 0.2.0

---

CHANGELOG.md
charts/timescaledb-single/templates/_helpers.tpl

Commit 188848d4111b77f98c7b3fa3878191d634981d06 introduced the
possibility to create separate WAL Volumes. With that change, the WAL
directory will now always be outside the PGDATA directory, even if the
Volume is the same.
We should therefore always set the wal_directory.
This came to light with error messages when running
`install [...] ""` where the wal_directory should have been inserted.
Backpatch to 0.2

Bugfix: Always set wal directory, regardles of Volumes

---

charts/timescaledb-single/admin-guide.md

The WAL Volume was enabled by default in
188848d4111b77f98c7b3fa3878191d634981d06, however the documentation did
not reflect this change.
I was wondering whether to revert the WAL Volume being enabled by
default or by patching the documentation, I think having separate
volumes should be the default, so I decided to change the documentation.
Backpatch to 0.2

Document that WAL Volume is enabled by default

---

CHANGELOG.md
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/README.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/values.yaml

Use TimescaleDB 1.5.0 for defaults for the timescaledb-single chart

Release v0.2.2

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/svc-timescaledb.yaml
charts/timescaledb-single/values.yaml

This feature allows you to annotate your load balancer with custom
annotations, which allows different kinds of load balancers as well as
load balancers that are internal instead of external.
The annotations that can be used are documented here:
https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html

Allow configuration of the Load Balancer

---

CHANGELOG.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

To allow metrics to be exported, we can run the postgres-exporter as a
sidecar to the database container.

Include a postgres-container in the Pod if enabled

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/sec-pgbackrest.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

To ensure we don't break current deployments, we do not yet deprecate
the old spelling.

Rename backup.enable to backup.enabled

---

CHANGELOG.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

According to the Kubernetes Documentation[1], this is how pods are
rescheduled currently:
... updating each Pod one at a time. It will wait until an updated
Pod is Running and Ready prior to updating its predecessor...
Without the readinessProbe the container running PostgreSQL was
considered Ready very quickly after startup. However, we can express
readiness much better by saying that it needs to *at least* be able to
connect to the PostgreSQL instance in the container before the container
can be marked ready.
This fixes a problem like the following scenario:
- An update to the Pod Template, requiring a rescheduling of all the
pods
- A somewhat large - or active - database that requires significant time
to be restored
What would happen is that a RollingUpdate strategy (which is the …

Include readinessProbe for PostgreSQL by default

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml

If the socket_directory would be changed somehow these lines would be
wrong, therefore use the template instead of using the literal.

Express socket directory using a template

---

CHANGELOG.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

During development it sometimes is useful to mimick certain situations,
like a delayed startup (due to a long-running restore for example), or
to allow you to execute a command in the container before the regular
commands start.
Another scenario where this may be useful is to aid in troubleshooting a
deployment, where by adding a long running sleep an operator may be able
to investigate or even solve a troublesome restore or startup of
PostgreSQL.

Allow a (debug) command to run at container start

---

CHANGELOG.md

Added
* Add [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes)
for PostgreSQL
* Allow a (debug) command to run at container startup
* Add a [Headless Service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) (by default),
with the option to convert it into a Load Balancer
Changed
* Rename backup.enable to backup.enabled for consistency, the old naming does still work.
* Rename postgresExporter to prometheus

Stamp release v0.2.5

---

CHANGELOG.md
charts/timescaledb-single/values.yaml

Patroni is pretty chatty by default, which is not needed in most
deployments.

Quiet down Patroni

---

charts/timescaledb-single/templates/pgbackrest.yaml

In commit 44b9e1fc6541226a9af33291c614a5cd7fc9e954 we renamed
backup.enable to backup.enabled, but somehow passed over this reference.

Ensure Backup Jobs are defined

---

CHANGELOG.md
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

Being able to annotate the pods created in the StatefulSet is
useful for being able to enable things like network policies, telling
the pod how to connect to other services, integration with things
like kiam, and more.

Add ability to set annotations on pods

---

CHANGELOG.md
charts/timescaledb-multinode/Chart.yaml
charts/timescaledb-multinode/admin-guide.md
charts/timescaledb-multinode/templates/statefulset-timescaledb-accessnode.yaml
charts/timescaledb-multinode/templates/statefulset-timescaledb-datanode.yaml
charts/timescaledb-multinode/values.yaml
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

There may be the need to run application specific logic after certain
events happen, e.g. database startup, database promotion etc.
To allow a pluggable way of expressing these callbacks, you can now
point to a ConfigMap which contains your callback scripts.
Keys that match any of these Patroni events:
- on_reload
- on_restart
- on_role_change
- on_start
- on_stop
Will be executed when these events happen.
An extra callback has been added for convenience which will always be
executed. (This also allows you to write a single script with some
conditional logic on the event that happened).
- all
Please refer to the Patroni manual for how these scripts should be
created and which arguments they are given:
https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql
(look for callbacks)

Use Patroni Callbacks if defined in ConfigMap

---

CHANGELOG.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

Previously, we attempted to restrict permissions of the socket by
setting `defaultMode` on the EmptyDir that serves the PostgreSQL socket.
This however is not a valid configuration option for EmptyDir[1], and
caused some issues when the Chart was deployed using for example Helm
2.14.0:
Error: validation failed: error validating "":
error validating data: ValidationError(StatefulSet.spec.template.spec.volumes[0].emptyDir):
unknown field "defaultMode" in io.k8s.api.core.v1.EmptyDirVolumeSource
By configuring the permissions using PostgreSQL parameters we achieve
what we set out to do: protect the socket for every user, and now we
actually do it correctly.
Addresses issue #57.
1: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#emptydirvolumesource-v1-core
defaultMode

Configure socket permissions in PostgreSQL

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml

Although PGDATA and PGHOST are not directly used by Patroni and
therefore by PostgreSQL, it is very convenient to have them defined
correctly.
In the case of PGDATA, chances are high that the value was actually
exposed incorrect previously, as many PostgreSQL Docker Images set the
PGDATA environment variable explicitly. This value is very likely to be
different from the Data directory that is used in this Helm Chart - even
more so as the Data directory can be configured directly by the user of
this chart.
By overriding PGDATA explicitly with the Data Directory we also pass on
to Patroni we ensure PGDATA is correct. Some immediate advantages:
- Executing a command that may rely on PGDATA just works (think:
pg_controldata)
- Callbacks called by Patroni have their environment setup correctly

Explicitly set PostgreSQL Environment Variables

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md

> NOTICE: When migrating from a 0.2.x chart to a 0.3 chart, please take the following into account:
- if you use the `env` key in your values, you should rewrite them from a
plain dict into a list of [EnvVar](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#envvar-v1-core)
* Add ability to [annotate](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) pods in the StatefulSet
* Add ability to run any script as callback, if exposed as a ConfigMap
* Reduce loglevel of Patroni from INFO to WARNING
* The values.yaml env key should be expressed as a list of [EnvVar](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#envvar-v1-core)s
* Refer to the latest minor versions for PostgreSQL & TimescaleDB
* Set `unix_socket_permissions` …

Release version 0.3.0

---

charts/timescaledb-single/values.yaml

The trigger for this update was a Digital Ocean deployment, which
requires volumes of at least 1Gi.
Update the max_wal_size/min_wal_size default parameters as well, to
ensure the wal volume can actually be used. The choice of 750MB is to
ensure the disk usage (by default) will remain below 80%, which is a
threshold that is very commonly configured in monitoring for alerts

Change Wal Volume Size from 1G to 1Gi

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/svc-timescaledb-replica.yaml
charts/timescaledb-single/templates/svc-timescaledb.yaml

Previously we used a headless service if the Load Balancer (LB) was
disabled for a given service. This however runs into an issue[1] which
cannot be easily solved without having to do manually
patch/remove/update some kubernetes objects.
To allow an easy path for upgrading a non-LB service to a LB service, we
change the service from being headless to being a ClusterIP service.
This allows users of the charts to upgrade by flipping `enabled=False`
to `enabled=True` for the service they want.
Changing the service from a LoadBalancer to a ClusterIP however does not
work currently, and requires some manual steps. As we cannot currently
solve this easily in the Helm chart we document the steps that allow
this upgrade to take place.
1: https://github.com/kubernetes/kubernetes/issues/11237

Switch services to ClusterIP if LB is disabled

---

charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/pgbackrest.yaml
charts/timescaledb-single/values.yaml

1: pgBackRest will balk on the flags `--scope` which are passed on by Patroni, so a wrapper script is required.
Inspiration:
https://github.com/zalando/patroni/blob/master/docs/replica_bootstrap.rst

WIP: Bootstrap from backup if available

---

CHANGELOG.md
charts/timescaledb-single/templates/configmap-scripts.yaml

In some scenario's it can be that the PGDATA directory is missing,
Patroni will remove the PGDATA directory for example if it is unable to
bootstrap a replica correctly.
When this situation occurs, pgBackRest will refuse to commence the
restore with the following error message:
ERROR: [073]: $PGDATA directory '/var/lib/postgresql/data' does not exist
Even though this can happen, it is not the normal sequence of events:
the PGDATA directory is explicitly created on container start.
If PGDATA does not exist it has to have been either Patroni or a (human)
operator that has removed this directory.
If Patroni removes PGDATA, it will also remove the WALDIR[1], and therefore
we will also have to recreate that sometimes.
1: https://github.com/zalando/patroni/blob/v1.6.3/patroni/postgresql/__init__ …

Create directories before restore if missing

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/templates/svc-prometheus.yaml
charts/timescaledb-single/values.yaml

Previously, even if you enabled Prometheus support, it was not
scrapeable because there was no service with the appropriate
annotations to tell Prometheus how to find it. To fix this, we now
deploy a service if Prometheus is enabled.
Further, to support more configuration of the Prometheus Postgres
exporter, we add the ability to specify env vars for specifically
the exporter container as well as volumes. This allows one to do
things like add custom queries to have their results exported with
other Prometheus metrics.

Make Prometheus scrapeable and add more config

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

This allows us to start to remove some secrets from the provided values,
which is something we've been asked a few times already.

Inject custom environment vars in backup container

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/networkpolicy.yaml
charts/timescaledb-single/values.yaml

For Kubernetes clusters that make use of NetworkPolicy and CNI, we
should provide a basic policy that they can extend with additional
rules.
To that end, this PR adds support for such a policy that makes sure
that all pods within the app can talk to one another (i.e. for
replication), can talk on the Patroni multicast channel for leader
races, and can communicate with backup scripts. Additionally, we
also have an ingress rule to allow Prometheus scrapers to connect
to the Prometheus endpoints. These ingress rules can be extended
by setting new rules under the 'networkPolicy.ingress' variable.

Add support for NetworkPolicies

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml

The install command should not fail if permissions are correct or if the
directories already exist. As a failure on the data directory or the wal
directory will also cause Patroni and PostgreSQL to fail, it seems
better to fail fast with the error message rather than to continue,
which will clutter the logs with more error messages.
For example in issue #72, the output would have been very clear that it
is a permission problem.

Fail fast on datadir or waldir issues

---

charts/timescaledb-single/templates/pgbackrest.yaml

The previous implementation worked just fine, however PR #76 introduces
another Job which uses curl to do the http calls.
This commit unifies the way we trigger http endpoints.

Use curl instead of wget to trigger pgBackRest backup

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

To ensure timescaledb-tune works well with a Patroni managed PostgreSQL
instance, we create a separate configuration file which is fully
generated by timescaledb.
We will then use the include directive of PostgreSQL configuration files
to load this file.
This means the order of evaluation of settings becomes as follows:
1. PostgreSQL compiled defaults
2. postgresql.example.conf from the package
3. timescaledb-tune generated file
4. Patroni: bootstrap.dcs.postgresql.parameters
5. Patroni: postgresql.parameters
6: Patroni: overrides (cluster-name for example)
This means that if `shared_buffers`, is not specified in the Patroni
configuration it will use the value of timescaledb-tune.
Timescaledb-tune is currently not very well suited to set min/max wal
size, so in order to tune those we do …

Run timescaledb-tune at pod initialization

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/job-update-patroni.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/templates/svc-timescaledb-config.yaml

Previously, changes in the `patroni.bootstrap.dcs` section of the
values.yaml would not propagate anywhere, as this section is only read
once (during initdb time), and then persisted in the DCS.
The documented way to update the dynamic configuration[1] is to:
1. update the DCS directly (kubectl edit ep/RELEASE-config)
2. or to send a PATCH to the /config endpoint[2] of Patroni
This commit implements option 2; it will connect to any running Patroni
to PATCH the config endpoint, for every update of the Helm Deployment.
The downside of option 1 is that it tries us to the DCS directly, whereas
Patroni can also use a separate etcd, consul etc, instead of relying on
Kubernetes endpoints.
1: https://patroni.readthedocs.io/en/latest/dynamic_configuration.html
2: …

Update Patroni DCS Configuration on Helm Update

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

To allow full flexibility of the timescaledb-tune process, we pass on
all arguments defined in the values.yaml.

Pass on arguments to timescaledb-tune

---

charts/timescaledb-single/values.yaml

DOM & DOW positions appear to be mixed up.
To verify based on a compliant cron syntax:
`00 02 * * 0`: [0200 every Sunday](https://crontab.guru/#00_02_*_*_0)
`00 02 * * 1-6`: [0200 every day-of-week from Monday through Saturday](https://crontab.guru/#00_02_*_*_1-6)

Update default cron schedules for backups

---

charts/timescaledb-single/templates/configmap-scripts.yaml

The check command of pgBackRest used to succeed on the replica, but this
behaviour changed recently [1] and will be ok in the long term.
This commit is a workaround for this change, and will only check the
backup stanza when running as primary.
Addresses issues #83 and #93
1: https://github.com/pgbackrest/pgbackrest/issues/878

Only verify backup stanza when running as a primary

---

charts/timescaledb-single/templates/role-timescaledb.yaml

For OpenShift explicit permissions for endpoints are required.
https://docs.openshift.com/container-platform/3.6/architecture/core_concepts/pods_and_services.html#endpoints
Addresses issue #91

Grant permissions to endpoints/restricted

---

charts/timescaledb-single/templates/pgbackrest.yaml

Fix #100 
Helm template output
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
name: timescaledb-incremental-daily
labels:
app: timescaledb
chart: timescaledb-single-0.5.1
release: timescaledb
heritage: Tiller
backup-type: incr
cluster-name: timescaledb
spec:
schedule: "12 02 * * 1-6"
concurrencyPolicy: Forbid
jobTemplate:
metadata:
labels:
app: timescaledb
chart: timescaledb-single-0.5.1
release: timescaledb
heritage: Tiller
backup-type: incr
cluster-name: timescaledb
spec:
activeDeadlineSeconds: 60
template:
metadata:
labels:
app: timescaledb
chart: timescaledb-single-0.5.1
release: timescaledb
heritage: Tiller
backup-type: incr
cluster-name: timescaledb
spec:
restartPolicy: OnFailure
containers:
- name: timescaledb-incr
image: curlimages/curl
command: ["/usr/bin/curl"]
args:
- …
```

Fix JSON formatting for backup cronjob

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml
charts/timescaledb-single/values/multiple-tablespaces.yaml

Add tablespace support during initialization
Larger deployments, or deployments that want to differentiate in Storage
type for their data (for example: cost reduction, performance increase)
*within* a single PostgreSQL instance will need to use multiple Volumes.
The only way to make this work is to use tablespaces in PostgreSQL.
This commit will - if defined - create tablespaces which point to a
Volume. This relation can only be made (currently, Kubernetes 1.16)
during the creation of the StatefulSet that serves all the PostgreSQL
instances.
The backup/restore sequence has been verified to work with the default
settings and backup enabled.

Add tablespace support during initialization

---

CHANGELOG.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

This allows more time between the WAL Volume exceeding the set
`max_wal_size` and the disk filling up, which in turn gives more time
for monitoring and alerting to notify an operator who in turn can
prevent an outage.

Reduce the dedicated max wal size from 80% to 60%

---

CHANGELOG.md
charts/timescaledb-single/templates/job-update-patroni.yaml
charts/timescaledb-single/templates/pgbackrest.yaml

The cluster-name label is used by Patroni to identify which Pods are
part of the replication topology.
Up to this commit, we labelled every component with the `cluster-name`
label for ease of selection, however, this has a major downside in that
when a Pod is not running Patroni, but it does have the same labels as
set in the PATRONI_KUBERNETES_LABELS environment variables, it is
considered to be part of the replication topology by Patroni.
Patroni *will* therefore create a replication slot for that pod
- which will never be removed as it is not a member of the topology.
Stale replication slots cause WAL pile up and at some point will cause
the WAL volume to fill up, which may cause the PostgreSQL instance to
become unavailable.
As this issue is only happening for pods, I decided to only …

Do not label Job Pods with cluster-name

---

charts/timescaledb-single/values/high_throughput.example.yaml

Using replication slots in high throughput situations has a significant
danger: The master may need to retain more WAL than the size of the WAL
Volume allows, if a replica is catching up.
With backup enabled: while the replica is catching up it will be
fetching archives from s3, until s3 is exhausted, after which the
replica will switch to streaming from the master. While the replica is
not yet streaming (this may take hours), the replication slot reserved
for it is stale and will cause WAL to be retained by the master.  If we
have a backup, we don't need replication slots, as s3 will have the WAL,
therefore, if the backup is enabled, we can safely disable the use of
replication slots.

Disable replication slots (high throughput example)

---

charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

Environment variables that are present at postmaster start may leak to
regular user sessions.
We therefore want to only pass along those environment variables that
are necessary for Patroni/PostgreSQL to function.
Patroni itself is aware of this, and therefore will already scrub all
the environment variables starting with PATRONI_ from the environment
before starting PostgreSQL, however, other environment variables may be
set that carry secrets, as that is quite a common setup in a Kubernetes
deployment.
To ensure the environment *is* available to callbacks, archive scripts,
backup scripts etc we store the environment before invoking Patroni and
we source the environment if any of these scripts are executed.
The immediate use case that is covered here is the exposing of S3 access …

Scrub the Patroni/PostgreSQL environment

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md

* Examples for setting up a High Throughput Cluster, or using different backup parameters
* Ability to override archive-push/archive-get pgBackRest settings
* Ability to use [envFrom](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables) to specify environment variables
* Update references to the latest Docker image (PostgreSQL 11.7). This also means PostGIS is now included
in the default Docker Image
* Remove all non-PostgreSQL/Kubernetes environment variables from Patroni/PostgreSQL
A regular user in PostgreSQL has the ability to read the environment variables of the
postmaster. Up to now, the chance of leaking secrets would have been small, but with
commit 9708c38b, it is now …

Release v0.5.4

---

charts/timescaledb-single/values.yaml

While benchmarking I ran into the situation that pods were not scheduled
evenly across all nodes of set of nodes.
The cause was that the labelSelector was using the wrong value in the
app label to match pods.

Use fullname for anti-affinity clause (bugfix)

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

The default size for /dev/shm in Kubernetes is 64MB, this however is not
sufficient for every deployment.
Addresses issue #127
For some background:
- Support Posix Shared Memory across containers in a pod
https://github.com/kubernetes/kubernetes/issues/28272
- Increase POSIX Shared Memory for Kubernetes
https://docs.okd.io/latest/dev_guide/shared_memory.html

Allow mounting /dev/shm from Memory

---

charts/timescaledb-single/templates/svc-timescaledb-replica.yaml
charts/timescaledb-single/templates/svc-timescaledb.yaml
charts/timescaledb-single/values.yaml

This provides control over the port which is to be exposed by the load
balancer, allowing multiple logical clusters to be exposed over
different load balancers without running into port conflicts.

Add (replica)loadBalancer.port config.

---

charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

By issuing a switchover *before* the pod is terminated, we avoid any
waits that may occur when the Pod is terminated while being a primary.
For relatively idle clusters, this brings the downtime of a primary pod
reschedule to something like 5 - 10 seconds.
For more active clusters, most of the time during shutdown is spent in
the final CHECKPOINT. However, the final CHECKPOINT is issued *after*
clients have already been disconnected, and no connections are allowed
anymore.
Very active clusters may take minutes to complete the CHECKPOINT, which
reduces the availability of the databases. By issuing a CHECKPOINT
*before* the actual shutdown commences, we may still take a significant
amount of time, but we establish 2 things:
1. Clients can still do their work, connect, read/write
2. The …

Improve speed of failover and recovery

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

When combining this chart in a release with other charts
that wish to initialize the database somehow it is easier
to have the callback config map name be templated.

Update the callbacks.configMap value to be templated

---

CHANGELOG.md
charts/repo/index.yaml
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/job-update-patroni.yaml

The previous definition of the Job would be required to succeed before
Helm would be satisfied.
The downside of this however is that if no Patroni is running no Helm
upgrades can be done.
If no Patroni's are running, patching the configuration is also not
important, as there are no running instances that require an immediate
reload.

Make patching of Patroni optional

---

charts/timescaledb-single/upgrade-guide.md

The guide presents a step by step approach
on how a user can edit their existing release
so the secrets are no longer managed by helm

Create an upgrade guide from 0.5.x to 0.6.0

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/unsafe_credentials.yaml
charts/timescaledb-single/values.yaml

During development and quick evaluation of the Helm Charts it is useful
to not worry about credentials too much.
Currently, some pre-installation steps are required to install this
Chart successfully. The value of those steps is that it ensures the
Secrets that are used are outside the control (and values) of Helm.
However, this is not as easy as generating some random credentials.
Therefore, introduce the unsafe boolean, it will create some random
credentials and a random certificate before installation.

Create random credentials once if unsafe == true

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/configmap-pgbackrest.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

In the previous tag, the default was set to 11, however this was not
propagated to either the PATH environment variable or the
patroni.postgresql.bin_dir, causing the behaviour to be broken.
Testing shows that the recovery options that were part of the pgBackRest
configuration are not required even for PostgreSQL 11, so we can remove
those lines altogether.
We still do need the option for someone to specify the version
explicitly, this allows someone to switch to a PostgreSQL 12 Docker
Image, while still running PostgreSQL 11, this allows you to decouple
the upgrading of Docker Images from running the pg_upgrade.

Use Docker Image PostgreSQL version by default

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml

a small fix for named port error with kubectl port-foward
$ kubectl port-forward svc/test-timescaledb-0 5432
error: Pod 'test-timescaledb-0' does not have a named port 'postgresql'
Issue #158

add name for containerPort: 5432

---

charts/timescaledb-single/admin-guide.md

Also, to address Issue #135, include an example for pgBackRest based
encryption configuration.

Clarify that secrets need to be base64 encoded

---

charts/timescaledb-single/generate_kustomization.sh

In Issue #156 it was reported that the script isn't working on MacOS.
Even though in commit f605da32 some fixes were already included to make
it work, it does not seem to suffice.
Also, actually exit the script if called without arguments.

Allow generate_kustomization to run on MacOS

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml

If timescaledb-tune was disabled, the log of the timescaledb container
would be showing a lot of:
LOG:  skipping missing configuration file "/var/run/postgresql/timescaledb.conf"
error messages. These are not harmful in any way, however they do
generate noise, which may confuse anyone looking at them.
By touching the file, we ensure the file is there, even if it's only
empty.

Prevent noisy warnings from being shown

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

This makes for a better experience IMHO, as previously, if you had
to add the key1: value1 annotation, you would have to:
```diff
- annotations: {}
+ annotations:
+   key1: value1
```
This also allows easier commenting out of things you do/do not want to
enable in the values.yaml
Whereas if we allow nil (and default it correctly in the templates) we
can make this change with the following diff:
```diff
+   key: value1
```

Allow most values to be nil in values.yaml

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

Reverts timescale/timescaledb-kubernetes#169
Although it works correctly, helm3 will now throw a lot of warnings:
```
coalesce.go:160: warning: skipped value for resources: Not a table.
coalesce.go:160: warning: skipped value for nodeSelector: Not a table.
coalesce.go:199: warning: destination for args is a table. Ignoring non-table value <nil>
coalesce.go:160: warning: skipped value for affinity: Not a table.
coalesce.go:199: warning: destination for pgBackRest:archive-get is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for pgBackRest:archive-push is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for annotations is a table. …
```

Revert "Allow most values to be nil in values.yaml"

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/configmap-pgbouncer.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/templates/svc-timescaledb-replica.yaml
charts/timescaledb-single/templates/svc-timescaledb.yaml
charts/timescaledb-single/values.yaml

pgBouncer[1] can be very useful in certain environments to limit the
number of connections established, or to limit the number of active
connections to the database.
There are quite a few deployment models for pgBouncer, and it boils down
to the following:
> Q: Should PgBouncer be installed on webserver or database server?
> A: It depends
https://www.pgbouncer.org/faq.html#should-pgbouncer-be-installed-on-webserver-or-database-server
This implementation is chosen, as other implementations can be done
outside of this Helm Chart. This implementation (a sidecar) however
requires to be integrated with the Helm Chart in order to work.
1: https://www.pgbouncer.org

Include option to run pgBouncer as a sidecar

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-pgbackrest.yaml
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

Currently, replica's will already use the S3 backups if they are
available to create a $PGDATA directory.
However, if no master (endpoint) is available, the behaviour up to now
was to always do an initdb.
This may not be what the user wants, say - a user wants to suspend a
service - removing all the Kubernetes objects and only keeping the S3
backups.
In such a scenario, it would be great if the backup would be used to
initialize the whole cluster.

Allow initialization of the cluster from backups

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/values/high_throughput.example.yaml

In commit 162c3838 the default was toggled to true, this brings the
documentation in line with the code.
Fixes GitHub issue #193

Document that tstune is enabled by default

---

CHANGELOG.md
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/values.yaml

All recent timescaledb-ha Docker Images have `lz4` available by default,
therefore every (recent) deployment should be able to use this.
This is also supported on existing stanza's:
https://github.com/pgbackrest/pgbackrest/issues/1103

Use lz4 compression method by default

---

.github/workflows/main.yml
CHANGELOG.md
Makefile
yaml2json.py

As a lot of things that are being done are in essence shell scripts, it
seems wise to actually lint/check these scripts for all example values
files.
The check is disabled until the time comes that all our scripts conform
to these checks.

Include shellcheck Makefile and CI targets

---

.github/workflows/main.yml
CHANGELOG.md
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.yaml

One of the toughest situations to resolve is the WAL Disk running out of
space. To recover from this, you either have to reclaim space, or extend
the volume size and the filesystem.
Extending the volume size is non-trivial in a Kubernetes context, and
reclaiming space is very hard, as WAL segments should never be (re)moved
manually, as they are essential to crash recovery of the PostgreSQL
instance.
(Having the Data Volumes run out of disk space is not that big of an
issue, as PostgreSQL can keep running).
This script and feature adds the possibility to verify that we're not
running out of diskspace for every time the archiver is invoked. By
doing it at that point in time, we can ensure the check is not executed
needlessly frequently on idle clusters, but it does get invoked often
for …

Prevent WAL disk from filling up

---

.github/workflows/push.yaml
Makefile
tests/values.yaml
tests/verify_deployment.sh
tests/wait_for_example_job.yaml

Introducing these tests gives us reasonable confidence that we're not
introducing a major error with the primary purpose of these Helm Charts:
to deploy a working set of Patroni managed PostgreSQL members.
The linter runs on every push, whereas the more extensive test, which
spins up all known values files, is only triggered if the Chart.yaml has
been changed in preparation of a release.

Run tests for all pushes

---

charts/timescaledb-single/templates/configmap-pgbouncer.yaml
charts/timescaledb-single/values.yaml

This is a minor refactor, putting the configmap values from the values.yaml at the END of the block instead of the beginning.
This allows for overriding of all options, specifically of importance is auth_query.
The reason for this is pgbouncer uses the last instance of a given configuration key, so in the orignial structure, adding an auth_query to the values.yaml resulted in that setting getting ignored, using the default from the template.
The same was true for all template-provided defaults.

Refactors pgbouncer configmap

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml

When you have quota on a namespace then try to add a timescaleDB in it, it will fail because of missing resources in init container.
Idk if you prefer to use same resources configuration than containers, if yes, there is the PR

Add resources to init container

---

charts/timescaledb-multinode/templates/_helpers.tpl
charts/timescaledb-multinode/templates/statefulset-timescaledb-accessnode.yaml
charts/timescaledb-multinode/templates/statefulset-timescaledb-datanode.yaml
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

By setting the Pod SecurityContext, we ensure every container inherits
these settings. The only field that cannot be set at the Pod level is
`allowPrivilegeEscalation`, therefore, we set that at the container
level.
By making the uid a template (which derives from values) we can more
easily set a different uid for all the processes involved.
Addresses issue #240.
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podsecuritycontext-v1-core
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#securitycontext-v1-core

Explicitly configure securityContext for pod

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/configmap-pgbouncer.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml
charts/timescaledb-single/values.yaml

Made the pgBouncer pg_hba into a list, as that is also how the Patroni
pg_hba is configured. It would be confusing if in the same `values.yaml`
there would be 2 separate ways of configuring the same category of
thing.
Added schema and documentation for these new pgBouncer configuration
items.

Refactor some pgBouncer features

---

charts/timescaledb-single/README.md

Got the below error while running the command from instructions. Checked the [helm install docs](https://helm.sh/docs/helm/helm_install/) and looks like there is no explicit name flag in newer versions. Removed the --name part and it ran without errors
helm install [NAME] [CHART] [flags]
  │  ~/c/h/timescaledb-single  helm install --namespace tsdb  --name tsdbtraining .                                                        
Error: unknown flag: --name
  │  ~/cloud/helmcharts/timescaledb-single  helm install --namespace tsdb  tsdbtraining .                                                        
NAME: tsdbtraining

Update helm command to remove name option

---

charts/timescaledb-single/templates/unsafe_credentials.yaml

This should simplify logic regarding handling credentials and potentially make "unsafe" mode obsolete.

charts: preserve secrets when upgrading chart in unsafe mode

---

charts/timescaledb-single/templates/statefulset-timescaledb.yaml

Bugfix - indentation of `data` volume annotations is wrong.

[timescaledb-single] Fix annotation indentation on data volume

---

charts/timescaledb-single/templates/secret-certificate.yaml
charts/timescaledb-single/templates/secret-patroni.yaml
charts/timescaledb-single/templates/secret-pgbackrest.yaml

By creating secrets before StatefulSet we can ensure existence of said secret and faster installation path.
This can also improve downstream usage in tobs as we can copy this secret to promscale secret earlier.

charts/timescaledb-single: create secrets before installation

---

charts/timescaledb-single/templates/secret-patroni.yaml
charts/timescaledb-single/templates/secret-pgbackrest.yaml

Since secrets are dynamically created during installation, it is worth keeping them after uninstall if someone would like to still access data on PV.
Note: This feature is currently implemented in tobs CLI. However, since we are moving Secrets ownership to this helm chart, it should live here. The feature is going to be removed from tobs CLI with https://github.com/timescale/tobs/pull/305

charts/timescaledb-single: keep database credentials after helm uninstall

---

charts/timescaledb-single/values.yaml

Bump default version of the database.

charts/timescaledb-single bump default version to pg14.2-ts2.6.1-p2

---

charts/timescaledb-single/templates/secret-patroni.yaml

Fixes #323
When providing additional credentials for patroni invalid yaml will be generation during helm template processing.
values.yaml
```yaml
secrets:
credentials:
PATRONI_test_PASSWORD: "test"
PATRONI_test2_PASSWORD: "test2"
```
secret-patroni without fix:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: "RELEASE-NAME-credentials"
labels:
app: RELEASE-NAME-timescaledb
cluster-name: RELEASE-NAME
type: Opaque
stringData:
PATRONI_SUPERUSER_PASSWORD: "Rlmv6dfg51cIPepM"
PATRONI_REPLICATION_PASSWORD: "8PeHhYkViGbJmysg"
PATRONI_admin_PASSWORD: "B6oaJhGNYp4mDTBA"  PATRONI_test2_PASSWORD: test2  PATRONI_test_PASSWORD: test
```
secret-patroni with fix:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: "RELEASE-NAME-credentials"
labels:
app: RELEASE-NAME-timescaledb
cluster-name: …
```

Fixed yaml parse when additional credentials are provided for patroni

---

charts/timescaledb-single/templates/secret-certificate.yaml
charts/timescaledb-single/templates/secret-patroni.yaml
charts/timescaledb-single/templates/secret-pgbackrest.yaml

It is not possible to do a lookup for `stringData` as this field does not exist in Secret object.

single: fix secret lookups

---

charts/timescaledb-single/values.yaml

This image contains the latest version of the Promscale extension,
required to work with Promscale 0.11.0

Bump timescaledb-ha docker image

---

charts/timescaledb-single/templates/secret-patroni.yaml
charts/timescaledb-single/templates/secret-pgbackrest.yaml

The YAML spec requires mapping keys to be unique and e.g. the Go YAML
parser used by Grafana Tanka errors out if that is not the case:
> line 1160: mapping key "annotations" already defined at line 1155

Fix duplicate "annotations" keys

---

charts/timescaledb-single/templates/role-timescaledb.yaml

This commit removes the permission to create services from the timescaledb role. The headless service is created by the helm chart itself, so the permission is not required in our case.
This works but causes a spam of `ERROR: create_config_service failed` in patroni logs. There is already an open issue about this on Patroni's repo zalando/patroni#1132, which once tackled will solve the log spam problem.
This PR also fixes the race in service deletion as reported in #397.
Signed-off-by: Prem Saraswat <prmsrswt@gmail.com>

timescaledb-single: Remove permission to create services

---

charts/timescaledb-single/admin-guide.md

The documentation neglects to mention the critical role of `pgbackrest` in the care and feeding of WAL data and the subsequent consequences of not configuring backups.
There is a mention of this in the comments buried deep within the chart itself [here](https://github.com/timescale/timescaledb-kubernetes/blob/88d1bb40521c93feed3b17785d7d1d5c1f56669e/charts/timescaledb-single/templates/configmap-scripts.yaml#L20), but it's not explicitly called out anywhere in any readme, leaving users to discover this information for themselves organically, which is very poor UX.
This PR attempts to correct that.

update documentation relevant to pgbackrest and wal maintenance

---

.github/workflows/release.yml
.gitignore

Doing `helm s3 push dist/* tscharts` can result in errors as seen in https://github.com/timescale/timescaledb-kubernetes/runs/7390426827?check_suite_focus=true#step:6:12
With this PR chart publishing job will go through all packaged charts and push them one by one instead of relying on shell globing.

*: improve publishing releases

---

charts/timescaledb-multinode/README.md

Update `README.md` to show that the multinode Helm chart is no longer being maintained.

Update README to indicate this Helm chart is no longer maintained.

---

charts/timescaledb-multinode/Chart.yaml
charts/timescaledb-multinode/requirements.yaml

Follow-up to https://github.com/timescale/helm-charts/pull/409

charts/timescaledb-multinode: deprecate chart

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/values.yaml

- Bump postgres_exporter to be inline to what we set inside tobs. 
- Update `admin-guide.md` to show new defaults for postgres_exporter.

Update default values for postgres_exporter and documentation

---

charts/avalanche/Chart.yaml
charts/avalanche/README.md
charts/avalanche/ci/default-values.yaml
charts/avalanche/templates/_helpers.tpl
charts/avalanche/templates/deployment-avalanche.yaml
charts/avalanche/templates/service-account.yaml
charts/avalanche/templates/service-monitor.yaml
charts/avalanche/templates/svc-avalanche.yaml
charts/avalanche/values.yaml
charts/timescaledb-multinode/Chart.yaml
charts/timescaledb-single/Chart.yaml

The PR adds a helm chart for running avalanche, a tool to load test Prometheus and Remote Write compatible storage backends, such as Promscale.
This fixes timescale/sre-monitoring#63

Add a helm chart for Avalanche

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/pgbackrest.yaml

Make sure we use the correct batch API version before 1.25+ removes the API 
```
warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

feat: make sure to use the correct batch api for crons

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/pgbackrest.yaml

Fix for Capabilities issue that I introduced (sorry about that)
was broken here https://github.com/timescale/helm-charts/pull/426
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
timescaledb-single:
- (root): Additional property global is not allowed
```
it does not need global scope

Fix capabilities

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/values.yaml

charts/timescaledb-single: bump used image versions

---

.github/workflows/tests.yml
Makefile
charts/promscale/Chart.yaml

* Bump promscale version from `0.13.0` to `0.14.0`
* Bump chart version from `13.0.0` to `14.0.0`

Update promscale to 0.14.0

---

charts/promscale/Chart.yaml
charts/promscale/templates/deployment-promscale.yaml
charts/promscale/values.yaml

Currently it is not possible using the helm chart to mount extra files to the deployment in order to configure extra functionalities like the alertmanager alerting rules according to:
https://docs.timescale.com/promscale/latest/alert/
In order to use the extra flag `-metrics.rules.config` is necessary to have the alertmanager files into the pod so the changes suggested here allows you to mount extra files from secrets or
configmaps according to the kubernetes options:
https://kubernetes.io/docs/concepts/storage/volumes/
I already performed some test locally configuring alerting rules and it works as expected, the Rule-Manager is started using the files mounted.
```
level=info ts=2022-09-14T10:24:49.657Z caller=runner.go:162 msg="Started Rule-Manager"
level=info ts=2022-09-14T10:24:49.657Z …
```

Allow mount extra volumes for config files

---

charts/promscale/Chart.yaml
charts/promscale/templates/deployment-promscale.yaml

Current pod annotation will result following result and make helm failed to deploy
```
STDERR:
Error: YAML parse error on xxx/charts/promscale/templates/deployment-promscale.yaml: error converting YAML to JSON: yaml: line 38: did not find expected key
Use --debug flag to render out invalid YAML
```
- fixes #

Fix pod annotation indentation

---

charts/promscale/Chart.yaml
charts/promscale/values.schema.json

Currently when we try to add affinities in the values.yaml file, it fails with a schema validation error. The schema for `affinity` is not correct and allows only empty object. This PR adds basic schema for this.

Add affinity schema to promscale chart

---

charts/avalanche/Chart.yaml
charts/avalanche/templates/deployment-avalanche.yaml
charts/avalanche/values.yaml

This adds the `tpl` function to the `extraArgs` configuration.  This is so we can render a templated value from `values.yaml`

Add template option to extraArgs

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/docs/admin-guide.md
charts/timescaledb-single/templates/podmonitor.yaml
charts/timescaledb-single/values.yaml

This makes monitoring via prometheus/podmonitor work once again in the chart.
#446 
I'm open to other paths here, but this simple fix got me moving again.  I removed the value for `podMonitor.portName` because the portName is hard-coded in the statefulset and doesn't seem like a terribly useful thing to be able to override in the values.
I _don't know_ where the motivation came from for the "component" selector.  I could be missing something here.  It at least doesn't exist in my deployments of the chart.  I removed it here, but if you know of a reason it should exists sometimes I'm glad to chat about it.

Bugfix for issue #446 - podmonitor not working in timescaledb-single.

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

The chart is set to always tune the settings for a specific PostgreSQL version (11) rather than the one actually being used. I am not certain what this will change in practice, but it does seem wrong to do so when there is no good reason.
- fixes #294

Removed -pg-version 11 from timescaledb-tune command

---

charts/avalanche/Chart.yaml
charts/avalanche/templates/deployment-avalanche.yaml
charts/avalanche/values.yaml

Since we will mostly use avalanche with `--remote-url` flag, disabling the `readinessProbe` by default would be nice, since Avalanche will not expose the `/health` endpoint with it enabled.

Update avalanche helm chart to disable readinessProbe by default

---

charts/promscale/Chart.yaml
charts/promscale/templates/deployment-promscale.yaml
charts/promscale/templates/prometheus-rule.yaml
charts/promscale/templates/svc-promscale.yaml
charts/promscale/values.yaml

Currently only ports 9201 and 9202 are enabled and it is not possible to enable a port with the helm chart to use the Thanos StoreAPI according to the configuration in
https://github.com/timescale/promscale/blob/master/docs/configuration.md using the param `thanos.store-api.server-address`.
I added the port configuration in the `values.yaml` and updated the deployment and service template, by default port will be set on false.
I already performed some test configuring the Thanos StoreAPI with:
```
config:
thanos.store-api.server-address: ":9203"
service:
thanosStoreAPI:
enabled: true
port: 9203
```
then checking the logs:
```
level=info ts=2022-09-19T16:22:29.822Z caller=runner.go:162 msg="Started Rule-Manager"
level=info ts=2022-09-19T16:22:29.822Z caller=runner.go:266 msg="Started …
```

Added possibility to enable thanos StoreAPI port

---

charts/avalanche/Chart.yaml
charts/avalanche/templates/statefulset-avalanche.yaml
charts/avalanche/values.yaml

This PR moves avalanche deployment mode to StatefulSet. This will give stable IDs to pods which can be used as replica label.

avalanche: Switch to StatefulSet for stable replica ID

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/docs/admin-guide.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml
charts/timescaledb-single/values.yaml

This PR adds support for setting resources on the `pgbackrest` container.
- fixes #264

feat(timescaledb-single): Allow setting resources for pgbackrest container

---

.github/renovate.json

Regular expression was not validating for the renovate configuration
- fixes #474

Fix regexp in renovate configuration

---

charts/promscale/Chart.yaml
charts/promscale/templates/prometheus-rule.yaml

Follow-up to https://github.com/timescale/promscale/pull/1714
- fixes #

charts/promscale: regenerate alerts

---

.github/renovate.json

Previous setting collided with our processes related to issues management and caused unnecessary notifications.
Previous setting collides with our processes related to issues management and causes unnecessary notifications.
- fixes #

.github: do not close dependency dashboard issue

---

charts/avalanche/Chart.yaml
charts/avalanche/templates/_helpers.tpl
charts/avalanche/values.yaml

This PR allows adding custom labels to all objects deployed via avalanche helm chart.
- fixes #

charts/avalanche: allow setting additional labels

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/svc-timescaledb.yaml

Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
This PR adds a missing k8s Service selector for timescaledb-single.
- fixes #

Add missing k8s Service selector for timescaledb-single

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/docs/admin-guide.md
charts/timescaledb-single/templates/podmonitor.yaml
charts/timescaledb-single/values.yaml

The field for target labels in a PodMonitor spec is called [podTargetLabels](https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/apis/monitoring/v1/types.go\#L1330). The `targetLabels` field only exists for service monitors.
The `targetLabels` field does not exist for pod monitors, but only for service monitors. To transfer labels when using a pod monitor, the field `podTargetLabels` should be used.

fix targetLabels field for pod monitor

---

charts/parca-agent/Chart.yaml
charts/parca-agent/README.md
charts/parca-agent/templates/_helpers.tpl
charts/parca-agent/templates/cluster-role-binding.yaml
charts/parca-agent/templates/cluster-role.yaml
charts/parca-agent/templates/daemonset.yaml
charts/parca-agent/templates/pod-security-policy.yaml
charts/parca-agent/templates/role.yaml
charts/parca-agent/templates/rolebinding.yaml
charts/parca-agent/templates/service-acccount.yaml
charts/parca-agent/templates/service.yaml
charts/parca-agent/values.yaml

This PR adds a helm chart for parca-agent. Together with the parca-server helm chart (#496) this can be used to deploy continuous profiling cluster wide.

Add helm chart for parca-agent

---

charts/avalanche/Chart.yaml
charts/avalanche/templates/service-monitor.yaml
charts/avalanche/values.yaml

Exposing this field would be useful to increase the number of samples being ingested into prometheus without incrasing the number of series.
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
- fixes #

Expose avalanche service monitor interval

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

This PR is an attempt to reduce code parametrization (effort needed to move some scripts out of a ConfigMap). It is done by statically reading ENV_FILE in each script. In the long term this will also allow to execute script with arbitrary file path, which is useful for development, as follows:
```
ENV_FILE="<path_to_file>" <script_name>.sh
```
This PR is part of effort from https://github.com/timescale/helm-charts/pull/505
PR is blocked by https://github.com/timescale/helm-charts/pull/515 and #516 
- fixes #

Static location for environment variables files

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/scripts/patroni_callback.sh
charts/timescaledb-single/scripts/pgbackrest_archive_get.sh
charts/timescaledb-single/scripts/pgbackrest_bootstrap.sh
charts/timescaledb-single/templates/configmap-scripts.yaml

Moving scripts out of being embedded in a ConfigMap template to a separate directory to allow easier code maintenance.
Following scripts are moved:
- patroni_callback.sh
- pgbackrest_bootstrap.sh
- pgbackrest_archive_get.sh
This PR is part of effort from https://github.com/timescale/helm-charts/pull/505
PR is blocked by https://github.com/timescale/helm-charts/pull/515, https://github.com/timescale/helm-charts/pull/516, and #517
- fixes #

Move patroni and pgbackrest scripts

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/scripts/pgbackrest_archive.sh
charts/timescaledb-single/scripts/pgbackrest_restore.sh
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

Moving and slightly refactoring (note new WALDIR environment variable) pgbackrest_archive.sh and pgbackrest_restore.sh scripts out of being embedded in a ConfigMap template to a separate directory to allow easier code maintenance.
This PR is part of effort from https://github.com/timescale/helm-charts/pull/505
PR is blocked by https://github.com/timescale/helm-charts/pull/515, https://github.com/timescale/helm-charts/pull/516,  https://github.com/timescale/helm-charts/pull/517, #518, and #519
- fixes #

Pgbackrest scripts migration

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/values.yaml

This is fixing upgrade path between 0.26 and 0.27 as reported in linked issue.
- fixes https://github.com/timescale/helm-charts/issues/531

timescaledb-single: do not remove everything on upgrade

---

charts/avalanche/Chart.yaml
charts/avalanche/templates/service-monitor.yaml

Signed-off-by: Harkishen Singh <harkishensingh@hotmail.com>
This commit allows to configure scrapeTimeout for Prometheus instances. This is particularly useful in benchmarks when scraping large targets with > 2M series, since then Prometheus needs more than 10s (default `scrapeTimeout`) to complete.

Add support to configure `scrapeTimeout` for Prometheus

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/pgbackrest.yaml

Linting the timescaledb-single chart with a helm 3.10.3 fails. 
https://github.com/timescale/helm-charts/issues/542 provides additional details and a fix.
- fixes #542
None

Prevent helm 3.10.3 linting failure

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/docs/admin-guide.md
charts/timescaledb-single/docs/upgrade-guide.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml
charts/timescaledb-single/values.yaml

Adding topologySpreadConstraints and removing `affinityTemplate` to allow easier handling of topology spread.
Defaulting to kubernetes defaults when it comes to handling topology
Signed-off-by: Paweł Krupa (paulfantom) <pawel@krupa.net.pl>
- Removal of `affinityTemplate` to allow only one way of setting affinity (via `affinity` field). This should simplify UX.
- Removing default affinity settings as the same is default in kubernetes 1.24+
- Adding option to set `topologySpreadConstraints`
- fixes #

charts/timescaledb-single: improve topology handling

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

Points patronictl to the correct config file.
This means that people can run the CLI without using `-c /etc/timescaledb/patroni.yaml`
Minimizes the risk of mistakes such as
#179
#347
#418

set patronictl config file

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/pgbackrest.yaml

Fixes a regression in [v0.32.0](https://github.com/timescale/helm-charts/releases/tag/timescaledb-single-0.32.0)
https://github.com/timescale/helm-charts/pull/558/files#diff-6ab02d41d428afe61e042df370a3f7e6d8eb6d3d4341223dd62e5c5196d3d867R37
There is a regression in v0.32.0 that results in this error when using the chart
`<.Values.curlImage.repository>: nil pointer evaluating interface {}.curlImage`
The problem happens because the scope changes here:
https://github.com/timescale/helm-charts/blob/555e38331a21ed1e3ecc6782a51117afbaf899df/charts/timescaledb-single/templates/pgbackrest.yaml#L23
so `.Values` is not accesible anymore:
https://github.com/timescale/helm-charts/blob/555e38331a21ed1e3ecc6782a51117afbaf899df/charts/timescaledb-single/templates/pgbackrest.yaml#L58-L59
To fix this, it …

Fix/curl image regression in v0.32.0

---

charts/timescaledb-single/scripts/pgbackrest_archive_get.sh
charts/timescaledb-single/scripts/pgbackrest_restore.sh

Recently, some heavy refactoring in the backup/restore procedure took place. This also changed the way how the environment variables etc were set up for the statefulset. 
With more recent helm chart versions, it is not possible anymore to restore a replica node from pgbackrest due to checking too early in script if backups are enabled or not. 
Furthermore, slaves are not able to fetch WAL from archive, leading to broken replicas (master already disposed WAL segment).
I ended up with a degraded cluster multiple times in the last weeks. This seems to fix it for me.
- fixes #574

check for enabled backup after sourcing environment

---

charts/timescaledb-single/Chart.yaml

Forgot to update the version update of the `timescale-single` chart in PR #581.
Updating it from 0.33.1 to 0.33.2 here.

Update semver to 0.33.2
