timescale/helm-charts

CHANGELOG.md
charts/timescaledb-multinode/Chart.yaml
charts/timescaledb-multinode/values.yaml
charts/timescaledb-single/Chart.yaml

Changed
* Use 2.0.0-beta3 Docker Image for multinode

Release 0.2.4 - Multinode Beta3

---

charts/timescaledb-single/admin-guide.md

checkpoint_completetion_target is a percentage, not a fixed data size.

fix checkpoint_completion_target value  in example

---

charts/timescaledb-single/templates/job-update-patroni.yaml

Point the update config job to the correct ep

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

Allow to load env vars using `envFrom` references

---

charts/timescaledb-single/values.yaml

Tune autovacuum for many chunks

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/svc-timescaledb-replica.yaml
charts/timescaledb-single/templates/svc-timescaledb.yaml
charts/timescaledb-single/values.yaml

This allows one to fully customize the Service's that are created using
the Helm Chart.
Author: Taylor Price <tayworm@gmail.com>
Changes by Feike Steenbergen

Allow overriding of all Service Spec items

---

.github/workflows/main.yml
.gitignore
Makefile
charts/timescaledb-multinode/Chart.yaml
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/values.yaml
charts/timescaledb-single/values/high_throughput.example.yaml
charts/timescaledb-single/values/m5.large.example.yaml

Introduce GitHub Actions.
The current job is very limited and only lints the Helm Charts, but future work will include checking of all values files against a schema, doing `shellcheck` for the scripts that are built etc.

Run linters/tests on PR's

---

.github/workflows/main.yml
Makefile

The test consists of creating a hypertable, which validates at least the
following:
- valid Docker Image
- valid Patroni configuration
- primary election succeeded
- timescaledb part of shared_preload_libraries
- timescaledb installed as an extension

Run smoketest when charts have changed

---

charts/timescaledb-multinode/Chart.yaml
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/configmap-scripts.yaml
ct.yaml

Commit ca7ffb9d added the quotes around the envdir call, however that is
wrong in this instance.

Export bootstrap environment correctly

---

Makefile
charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml
charts/timescaledb-single/values.yaml
tests/custom-init-scripts.yaml

This commit depends on https://github.com/zalando/patroni/pull/1631, which now has been merged,
however it is part of Patroni 2.0. We therefore should take care not to merge this one before we have Patroni 2.0 support
in the Docker image
Addresses GitHub issue #102

WIP: Allow custom Post Init scripts to be run

---

.github/workflows/push.yaml

.github: run CI workflows on PRs from forks

---

.github/workflows/push.yaml

Update to use newer helm in CI test.

.github: update github actions to latest versions

---

charts/timescaledb-single/templates/NOTES.txt
charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/secret-patroni.yaml
charts/timescaledb-single/templates/secret-pgbackrest.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

fixed setting secrets.credentialsSecretName doesn't do anything

---

charts/timescaledb-single/admin-guide.md
charts/timescaledb-single/values.yaml

Same as https://github.com/timescale/timescaledb-kubernetes/pull/287, just rebased. Relates to https://github.com/timescale/tobs/issues/481
Closes https://github.com/timescale/timescaledb-kubernetes/pull/287

feat: upgrade postgres-exporter to latest version

---

charts/timescaledb-single/templates/_helpers.tpl
charts/timescaledb-single/templates/configmap-patroni.yaml
charts/timescaledb-single/templates/configmap-pgbackrest.yaml
charts/timescaledb-single/templates/configmap-pgbouncer.yaml
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/job-update-patroni.yaml
charts/timescaledb-single/templates/networkpolicy.yaml
charts/timescaledb-single/templates/pgbackrest.yaml
charts/timescaledb-single/templates/role-timescaledb.yaml
charts/timescaledb-single/templates/rolebinding-timescaledb.yaml
charts/timescaledb-single/templates/secret-certificate.yaml
charts/timescaledb-single/templates/secret-patroni.yaml
charts/timescaledb-single/templates/secret-pgbackrest.yaml
charts/timescaledb-single/templates/serviceaccount-timescaledb.yaml
charts/timescaledb-single/templates/servicemonitor.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/templates/svc-prometheus.yaml
charts/timescaledb-single/templates/svc-timescaledb-config.yaml
charts/timescaledb-single/templates/svc-timescaledb-replica.yaml
charts/timescaledb-single/templates/svc-timescaledb.yaml

* Add common labels to be used by all templates

Change service name and add labels

---

.github/CODEOWNERS

Add `CODEOWNERS` file to repo.

Add codeowners to repo

---

charts/timescaledb-single/templates/configmap-patroni.yaml
charts/timescaledb-single/templates/configmap-pgbackrest.yaml
charts/timescaledb-single/templates/configmap-pgbouncer.yaml
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/job-update-patroni.yaml
charts/timescaledb-single/templates/networkpolicy.yaml
charts/timescaledb-single/templates/pgbackrest.yaml
charts/timescaledb-single/templates/role-timescaledb.yaml
charts/timescaledb-single/templates/rolebinding-timescaledb.yaml
charts/timescaledb-single/templates/secret-certificate.yaml
charts/timescaledb-single/templates/secret-patroni.yaml
charts/timescaledb-single/templates/secret-pgbackrest.yaml
charts/timescaledb-single/templates/serviceaccount-timescaledb.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/templates/svc-timescaledb-config.yaml
charts/timescaledb-single/templates/svc-timescaledb-replica.yaml
charts/timescaledb-single/templates/svc-timescaledb.yaml

Make sure that `namespace` is always defined in templates.

Update templates to make sure namespace is set

---

.github/workflows/tests.yml
Makefile
charts/promscale/Chart.yaml
charts/promscale/README.md
charts/promscale/ci/default-values.yaml
charts/promscale/templates/_helpers.tpl
charts/promscale/templates/config.yaml
charts/promscale/templates/deployment-promscale.yaml
charts/promscale/templates/prometheus-rule.yaml
charts/promscale/templates/secret-connection.yaml
charts/promscale/templates/service-account.yaml
charts/promscale/templates/service-monitor.yaml
charts/promscale/templates/svc-promscale.yaml
charts/promscale/values.schema.json
charts/promscale/values.yaml
scripts/generate-promscale-alerts.sh

This PR migrates promscale helm chart code from https://github.com/timescale/promscale/tree/master/deploy/helm-chart. It also moves tooling necessary for maintenance of this helm chart.
- fixes #

Move promscale helm chart

---

Makefile
charts/timescaledb-single/ci/defaults-values.yaml
charts/timescaledb-single/examples/high_throughput.example.yaml-values.yaml
charts/timescaledb-single/examples/m5.large.example.yaml-values.yaml
charts/timescaledb-single/examples/multiple-tablespaces-values.yaml
charts/timescaledb-single/examples/pgbouncer_customizations-values.yaml

Migrating shell script based testing method to chart-testing utility to align with other charts.
- fixes #

WIP: charts/timescaledb-single: enable ct as a testing suite

---

.github/workflows/release.yml
ct.yaml

With this PR we'll have a more robust release process which would do the following:
1) Find out latest published git tag
2) Find out which chart that was recently modified
3) Find out new chart version
4) Create helm package for chart from previous point and publish it
5) Create GitHub release and tag based on the following template: `<CHART_NAME>-<CHART_VERSION>`
This assumes we are bumping chart versions on each PR. To enforce such behavior this PR is also reconfiguring `ct`.
- fixes #

.github: refactor release process

---

.github/labeler.yml
.github/workflows/project-management.yml

This allows to have more visibility into what the PR is about without reading title or opening the PR.
- fixes #

Automatically label all PRs to note the area of work

---

CHANGELOG.md
CONTRIBUTING.md
README.md

Bringing project docs up to date.

---

.github/workflows/project-management.yml
charts/promscale/Chart.yaml
charts/promscale/README.md
charts/promscale/UPGRADING.md
charts/promscale/templates/secret-connection.yaml

As in title.
This is also aligning versioning schema with one we have in tobs.
Merging this will also test our automated release pipeline.
- fixes  https://github.com/timescale/promscale/issues/1474
- closes https://github.com/timescale/promscale/pull/1475

chart/promscale: remove flaky logic for setting connection params

---

.github/workflows/release.yml
CONTRIBUTING.md
charts/timescaledb-multinode/Chart.yaml
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/values.yaml
ct.yaml

Aligning with other projects managed by Services Team.
- fixes #

*: change branch name to main

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/pgbackrest.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml

Resolves issue with schema
- fixes https://github.com/timescale/helm-charts/issues/433
I should have tested this first, sorry this should resolve all issues now.

fix schema and chart

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml

Fix `values.yaml` schema validation if this chart is used as a dependency in another chart
- fixes #436

Fix chart schema validation if used as dependency

---

.github/workflows/project-management.yml
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/configmap-scripts.yaml

Signed-off-by: Paweł Krupa (paulfantom) <pawel@krupa.net.pl>
Closes #449 
Fixes #442
We need to merge this ASAP hence recreation of #449 PR with added chart version bump.
- fixes #

Fixed wrong exit code in restore script when backup is disabled

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml
charts/timescaledb-single/values.yaml

This PR allows setting labels to the StatefulSet pod which are needed for us to filter by them in different tools like Prometheus or OpenCost.

allow adding labels to StatefulSet pods

---

.github/renovate.json
Makefile
charts/promscale/Chart.yaml

- Including promscale 0.15.0 image as a default image
- attempting to improve automatic updates of promscale image via renovate
- fixes #

Promscale 0.15

---

Makefile
charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/README.md
charts/timescaledb-single/ci/defaults-values.yaml
charts/timescaledb-single/docs/admin-guide.md
charts/timescaledb-single/docs/upgrade-guide.md
charts/timescaledb-single/templates/svc-timescaledb-replica.yaml
charts/timescaledb-single/templates/svc-timescaledb.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml
charts/timescaledb-single/values.yaml

Signed-off-by: Paweł Krupa (paulfantom) <pawel@krupa.net.pl>
This is part of simplifying the helm chart and removing duplicated or deprecated code.
~This PR is also enabling upgrade tests with chart-testing suite.~
- fixes #

charts: deprecate loadbalancer SVCs

---

.github/workflows/push.yaml
.github/workflows/release.yml
charts/promscale/Chart.yaml
charts/promscale/templates/prometheus-rule.yaml

This will fix the failing CI jobs in #481 
- fixes #481

Fix CI build issues

---

charts/avalanche/Chart.yaml
charts/avalanche/templates/statefulset-avalanche.yaml
charts/avalanche/values.yaml

Signed-off-by: Paweł Krupa (paulfantom) <pawel@krupa.net.pl>
Adding options to allow pod placing (tolerations, affinity, node selector). This PR is also cleaning code a bit by using [`nindent` instead of `indent`.](http://masterminds.github.io/sprig/strings.html#:~:text=nindent,the%20beginning%20of%20the%20string.&text=nindent%204%20%24lots_of_text-,The%20above%20will%20indent%20every%20line%20of%20text%20by%204,new%20line%20to%20the%20beginning.) 
- fixes #

chart/avalanche: add options related to pod placing

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml
charts/timescaledb-single/values.schema.json
charts/timescaledb-single/values.schema.yaml
charts/timescaledb-single/values.yaml

charts/timescaledb-single: allow configuring CLI parameters of postgres_exporter

---

charts/parca-server/Chart.yaml
charts/parca-server/README.md
charts/parca-server/templates/_helpers.tpl
charts/parca-server/templates/config.yaml
charts/parca-server/templates/deployment.yaml
charts/parca-server/templates/pod-security-policy.yaml
charts/parca-server/templates/role.yaml
charts/parca-server/templates/rolebinding.yaml
charts/parca-server/templates/service-acccount.yaml
charts/parca-server/templates/service.yaml
charts/parca-server/values.yaml

This PR adds a new helm chart for parca-server. 
- fixes #

Add helm chart for parca-server

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/scripts/tstune.sh
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

As in title. PR is part of effort from https://github.com/timescale/helm-charts/pull/505
- fixes #

charts/timescaledb-single: move tstune script outside of helm templates

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/scripts/post_init.sh
charts/timescaledb-single/templates/configmap-scripts.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

Moving and slightly refactoring (note TABELSPACES envrionment variable handling) post_init.sh script out of being embedded in a ConfigMap template to a separate directory to allow easier code maintenance.
This PR is part of effort from https://github.com/timescale/helm-charts/pull/505
PR is blocked by https://github.com/timescale/helm-charts/pull/515, https://github.com/timescale/helm-charts/pull/516,  https://github.com/timescale/helm-charts/pull/517, and #518 
- fixes #

Post init script migration

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/pgbackrest.yaml

Single timescale chart do not renders properly
Wrong scope passed into helper function inside range in bgbackrest.yaml
- fixes #

Fixing scope in label templating

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/statefulset-timescaledb.yaml

charts/timescaledb-single: fix checksuming of tstune args

---

charts/promscale/Chart.yaml
charts/promscale/templates/prometheus-rule.yaml
charts/timescaledb-single/Chart.yaml

charts/promscale: updated alerting rules

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/values.yaml

charts/timescaledb-single: bump image to pg14.6-ts2.9.1-p1

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/templates/job-update-patroni.yaml

Use helm revision number instead of random number for patroni reloader job

---

charts/promscale/README.md

Add note about Promscale being discontinued

---

README.md

Signed-off-by: Ramon Guiu <ramon@timescale.com>
- fixes #

Remove link to Promscale

---

charts/timescaledb-single/Chart.yaml
charts/timescaledb-single/scripts/pgbackrest_archive.sh
charts/timescaledb-single/scripts/pgbackrest_archive_get.sh

Fix timescaledb single 0.3.22 release

---

README.md

Unmaintained note in README
